sudo: false
notifications:
  irc: "chat.freenode.net#horde"
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
before_script:
  - phpenv config-rm xdebug.ini || echo "XDebug not enabled"
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ] || [ "$TRAVIS_PHP_VERSION" == "7.0" ];
    then
      echo "include_path = .:$HOME/.phpenv/versions/$(phpenv version-name)/lib/php/pear" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
      pear channel-discover pear.horde.org;
    fi

  - pear install channel://pear.horde.org/Horde_Test
  - pear install package.xml
script:
  - php $(find test -name AllTests.php)
